# Generated by Django 5.1 on 2024-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User'), ('user1', 'User1'), ('user2', 'User2'), ('user3', 'User3'), ('user4', 'User4')], default='staff', max_length=20, verbose_name='Role'),
        ),
    ]
