# Generated by Django 5.1 on 2024-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='window_number',
            field=models.IntegerField(default=112, verbose_name='window_number'),
        ),
    ]
