# Generated by Django 5.1 on 2024-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0002_fileprocess_created_at_fileprocess_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
