# Generated by Django 5.1 on 2024-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0004_serviceavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='file_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('start', 'Start'), ('checked', 'Checked'), ('scanned', 'Scanned'), ('recorded', 'Recorded')], default='start', max_length=10),
        ),
    ]
