# Generated by Django 5.1 on 2024-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0005_alter_fileprocess_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocess',
            name='driver_lisence_number',
            field=models.CharField(default='435834', max_length=255),
        ),
        migrations.AddField(
            model_name='fileprocess',
            name='license_type',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('level4', 'Level 4'), ('level5', 'Level 5'), ('level6', 'Level 6')], default='level 1', max_length=255),
        ),
        migrations.AddField(
            model_name='fileprocess',
            name='owner_name',
            field=models.CharField(default='Abebe Alemu Teshale', max_length=255),
        ),
        migrations.AddField(
            model_name='fileprocess',
            name='plate_code',
            field=models.CharField(choices=[('plate1', 'plate one'), ('plate2', 'plate two'), ('plate3', 'plate three'), ('plate4', 'plate four')], default='plate code one', max_length=255),
        ),
        migrations.AddField(
            model_name='fileprocess',
            name='region',
            field=models.CharField(choices=[('aa', 'Addis Ababa'), ('et', 'Ethiopia')], default='aa', max_length=255),
        ),
        migrations.AddField(
            model_name='fileprocess',
            name='service_type',
            field=models.CharField(choices=[('service1', 'Service one'), ('service2', 'Service Two'), ('service3', 'Service Three'), ('service4', 'Service Four'), ('service5', 'Service Five'), ('service6', 'Service Six'), ('service7', 'Service Seven'), ('service8', 'Service Eight'), ('service9', 'Service Nine')], default='service type one', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='file_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
