# Generated by Django 5.1 on 2024-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0006_fileprocess_driver_lisence_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocess',
            name='service_for',
            field=models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle')], default='driver', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='owner_name',
            field=models.CharField(default='Abebe Alemu', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='service_type',
            field=models.CharField(choices=[('service1', 'Service one'), ('service2', 'Service Two'), ('service3', 'Service Three'), ('service4', 'Service Four')], default='service type one', max_length=255),
        ),
    ]
