# Generated by Django 5.1 on 2024-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0007_fileprocess_service_for_alter_fileprocess_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='license_type',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('level4', 'Level 4'), ('level5', 'Level 5'), ('level6', 'Level 6')], default='level1', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='plate_code',
            field=models.CharField(choices=[('plate1', 'plate one'), ('plate2', 'plate two'), ('plate3', 'plate three'), ('plate4', 'plate four')], default='plate1', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='service_type',
            field=models.CharField(choices=[('service1', 'Service one'), ('service2', 'Service Two'), ('service3', 'Service Three'), ('service4', 'Service Four')], default='service1', max_length=255),
        ),
    ]
