# Generated by Django 5.1 on 2024-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0008_alter_fileprocess_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='driver_lisence_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='license_type',
            field=models.CharField(blank=True, choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('level4', 'Level 4'), ('level5', 'Level 5'), ('level6', 'Level 6')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='plate_code',
            field=models.CharField(blank=True, choices=[('plate1', 'plate one'), ('plate2', 'plate two'), ('plate3', 'plate three'), ('plate4', 'plate four')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='region',
            field=models.CharField(blank=True, choices=[('aa', 'Addis Ababa'), ('et', 'Ethiopia')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='service_for',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('vehicle', 'Vehicle')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileprocess',
            name='service_type',
            field=models.CharField(blank=True, choices=[('service1', 'Service one'), ('service2', 'Service Two'), ('service3', 'Service Three'), ('service4', 'Service Four')], max_length=255, null=True),
        ),
    ]
