# Generated by Django 5.1 on 2024-09-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0009_alter_fileprocess_driver_lisence_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprocess',
            old_name='driver_lisence_number',
            new_name='driver_license_number',
        ),
    ]
