# Generated by Django 5.1 on 2024-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0010_rename_driver_lisence_number_fileprocess_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='file_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('fileout', 'FileOut'), ('start', 'Start'), ('checked', 'Checked'), ('scanned', 'Scanned'), ('recorded', 'Recorded')], default='start', max_length=10),
        ),
    ]
