# Generated by Django 5.1 on 2024-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileprocess', '0012_alter_fileprocess_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocess',
            name='file_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('fileout', 'FileOut'), ('uncheck', 'Unchecked'), ('start', 'Start'), ('checked', 'Checked'), ('scanned', 'Scanned'), ('recorded', 'Recorded'), ('disapproved', 'Disapproved'), ('nofile', 'NoFile')], default='start', max_length=15),
        ),
    ]
