# Generated by Django 5.0.6 on 2024-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_room', models.IntegerField()),
                ('end_room', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_room'],
            },
        ),
        migrations.CreateModel(
            name='UserObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
            ],
        ),
    ]
