# Generated by Django 5.0.6 on 2024-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_officedirection_userobligation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10)),
            ],
        ),
    ]
