# Generated by Django 5.1 on 2024-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_ticketannouncement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketannouncement',
            old_name='ticket_number',
            new_name='current_ticket_number',
        ),
        migrations.AddField(
            model_name='ticketannouncement',
            name='last_ticket_number',
            field=models.CharField(default=45, max_length=10),
        ),
        migrations.AddField(
            model_name='ticketannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
