# Generated by Django 5.1 on 2024-08-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_ticket_number_ticketannouncement_current_ticket_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketannouncement',
            name='last_ticket_number',
            field=models.CharField(max_length=10),
        ),
    ]
