# Generated by Django 5.1 on 2024-08-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='level_of_satisfaction',
            new_name='level_of_satsfaction',
        ),
    ]
