# Generated by Django 5.0.6 on 2024-08-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_level_of_satisfaction_comment_level_of_satsfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.CharField(default=123, max_length=10),
        ),
    ]
