# Generated by Django 5.0.6 on 2024-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='window_number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
