# Generated by Django 5.0.6 on 2024-08-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_window_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticket_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
