# Generated by Django 5.0.6 on 2024-08-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_ticket_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='level_of_satsfaction',
            new_name='level_of_satisfaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='level_of_comment',
            field=models.CharField(choices=[('general', 'General'), ('touser', 'To User')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
