# Generated by Django 5.0.6 on 2024-08-21 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_rename_level_of_satsfaction_comment_level_of_satisfaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('level_of_satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='level_of_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.CharField(default='34', max_length=10),
        ),
    ]
