# Generated by Django 5.0.6 on 2024-08-19 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAndVehicleStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('service_name', models.TextField(unique=True)),
                ('service_time', models.IntegerField()),
                ('service_quality', models.IntegerField()),
                ('service_type', models.CharField(choices=[('driver', 'DRIVER'), ('vehicle', 'VEHICLE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPrerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='services.driverandvehiclestandards')),
            ],
        ),
    ]
